passFilter = 'PASS'

variantConsequencePriorityList = [
    "bidirectional_gene_fusion",
    "gene_fusion",
    "unidirectional_gene_fusion",
    "frameshift_variant",
    "stop_gained",
    "stop_lost",
    "start_lost",
    "transcript_ablation",
    "transcript_amplification",
    "splice_donor_variant",
    "splice_acceptor_variant",
    "inframe_deletion",
    "inframe_insertion",
    "missense_variant",
    "protein_altering_variant",
    "splice_region_variant",
    "coding_sequence_variant",
    "incomplete_terminal_codon_variant",
    "start_retained_variant",
    "stop_retained_variant",
    "synonymous_variant",
    "copy_number_decrease",
    "copy_number_increase",
    "copy_number_change",
    "mature_miRNA_variant",
    "five_prime_UTR_variant",
    "three_prime_UTR_variant",
    "transcript_variant",
    "regulatory_region_ablation",
    "regulatory_region_amplification",
    "regulatory_region_variant",
    "feature_elongation",
    "feature_truncation",
    "intron_variant",
    "five_prime_duplicated_transcript",
    "non_coding_transcript_exon_variant",
    "non_coding_transcript_variant",
    "short_tandem_repeat_expansion",
    "short_tandem_repeat_contraction",
    "short_tandem_repeat_change",
    "three_prime_duplicated_transcript",
    "NMD_transcript_variant",
    "upstream_gene_variant",
    "downstream_gene_variant",
    "intergenic_variant"
]


cnvConsequencePriorityList = [
    "copy_number_decrease",
    "copy_number_increase",
    "transcript_ablation",
    "transcript_amplification",
    "regulatory_region_ablation",
    "regulatory_region_amplification",
    "regulatory_region_variant",
    "feature_truncation",
    "feature_elongation",
    "five_prime_duplicated_transcript",
    "three_prime_duplicated_transcript"
]

""" variantTypeKBCategoryMap = dict( copy_number_loss="copy loss",
                             copy_number_gain="copy gain",
                             deletion="deep deletion",
                             tandem_duplication="increased expression",
                             complex_structural_alteration="copy variant",
                             copy_number_variation="copy variant",
                             delins="shallow deletion",
                             duplication="low level copy gain",
                             insertion="copy variant",
                             inversion="copy variant",
                             mobile_element_deletion="copy variant",
                             mobile_element_insertion="copy variant"
                             ) """
                             
variantTypeKBCategoryMap = dict( copy_number_loss="deep deletion",
                             copy_number_gain="amplification",
                             deletion="deep deletion",
                             tandem_duplication="amplification",
                             complex_structural_alteration="low level copy gain",
                             copy_number_variation="low level copy gain",
                             delins="deep deletion",
                             duplication="amplification",
                             insertion="amplification",
                             inversion="amplification",
                             mobile_element_deletion="deep deletion",
                             mobile_element_insertion="amplification"
                             )